# Generated by Django 5.0.3 on 2024-04-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://example.com/default-image.jpg', max_length=2048),
        ),
    ]
